### ISSUE TITLE
Issue loading PlayerAPI on React 16 with Next 9.4

### ISSUE THREAD

**Issue by atresca-globant** [IBM/video-streaming-web-player-api#7]
Hello guys, 

We are implementing a streaming solution using this player and we are having problems with the PlayerAPI module. 
We are able to see the streaming(broadcasting with OBS) working on the iframe if we don't import the API module, but once we import it the page breaks.

Do you know if is something related to Next.js ? Or if we are missing something on our side?
Thanks in advance.

**Using** 
React 16.13.1
Next 9.4.4
ibm-video-streaming-web-player-api  1.2.0 (also tried 1.1.0)

**Browser logs**
![image](https://user-images.githubusercontent.com/72890641/112528767-4c950980-8d83-11eb-9731-6e73cf44a8f3.png)

**Console logs**
![image](https://user-images.githubusercontent.com/72890641/112529124-b1506400-8d83-11eb-88d0-5383458cad38.png)

**VSCode warning**
![image](https://user-images.githubusercontent.com/72890641/112529321-e6f54d00-8d83-11eb-8f95-2723c7443403.png)

**Comment by jungdaniel** [comment]
Hi @atresca-globant

You are trying to use this library with server side rendering, right? This lib contains parts that only makes sense in the context of a browser. One thing that could work is to use dynamic import though.

I was thinking of something like this:
```javascript
import React, { useEffect, useRef, useState } from 'react';

export const IBMVideoStreamingEmbed = ({ src }) => {
  const iframeRef = useRef(null);
  const [playerAPI, setPlayerApi] = useState(null);

  useEffect(async () => {
      const { current: iframe } = iframeRef;
      if (!iframe) {
        return;
      }
  
      const { default: PlayerAPI } = await import('ibm-video-streaming-web-player-api');
      setPlayerApi(new PlayerAPI(iframe));
  }, [iframeRef]);
  
  const onPlay = () => {
    if (!playerAPI) {
      return;
    }
    
    playerAPI.callMethod('play');
  }

  return (
     <div>
       <iframe
          ref={iframeRef}
          src={src}
          // other attributes
       />
       <button onClick={onPlay}>
          Play
        </button>
     </div>
  );
}
```

Let me know if this helped.

Are you using typescript? Would you benefit from having `@types/ibm-video-streaming-web-player-api` declarations available?
